#!/bin/sh

# softether 包装器加入开机序列（是否真起仍由界面开关控制）
[ -x /etc/init.d/softethervpn ] && /etc/init.d/softethervpn enable

# 默认主机名 StarNetWrt
uci -q set system.@system[0].hostname='StarNetWrt'

# 时区：Asia/Shanghai (UTC+8)。CST-8 为 POSIX 写法，zonename 供 LuCI/zoneinfo 使用
uci -q set system.@system[0].timezone='CST-8'
uci -q set system.@system[0].zonename='Asia/Shanghai'
uci -q commit system

# 默认 LAN IP：192.168.1.1 -> 192.168.10.1/24
# 新版为 CIDR list ipaddr，需先删旧值再 add_list（在 config_generate 之后执行）
uci -q delete network.lan.ipaddr
uci -q add_list network.lan.ipaddr='192.168.10.1/24'
uci -q commit network

# LuCI 默认简体中文
uci -q set luci.main.lang='zh_cn'
uci -q commit luci

# nlbwmon：官方包默认不启用开机服务，导致 LuCI 流量页无数据
/etc/init.d/nlbwmon enable
/etc/init.d/nlbwmon start

# PushBot：默认 pushbot_enable=0 会导致启动即自杀
if uci -q show pushbot >/dev/null 2>&1; then
	uci -q set pushbot.pushbot.pushbot_enable='1'
	uci -q commit pushbot
	/etc/init.d/pushbot enable
	/etc/init.d/pushbot restart
fi

# Zabbix agentd：UCI general.enabled 默认 0，
# init 读到 0 直接退出，表现为 active with no instances
if uci -q show zabbix_agentd >/dev/null 2>&1; then
	uci -q set zabbix_agentd.general.enabled='1'
	uci -q commit zabbix_agentd
	/etc/init.d/zabbix_agentd enable
	/etc/init.d/zabbix_agentd start
fi

exit 0
